// declarations for direct child modules                          
pub mod lib_one;   // file
pub mod entities;  // folder of modules

// below this is generated by cargo

/*
pub fn add(left: u64, right: u64) -> u64 {
  left + right
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn it_works() {
    let result = add(2, 2);
    assert_eq!(result, 4);
  }
}
*/
